from urllib.request import urlopen
from pathlib import Path

EXTRA_MESSAGE = """\

..  AUTOGENERATED by scripts/kitchen_sink_update.py

..  note::

    The Kitchen Sink was generated from the `Sphinx Themes website <https://sphinx-themes.org/>`_, a community-supported showcase of themes for `Sphinx <https://www.sphinx-doc.org/>`_.
    Check it out to see other great themes.
    
    ..  button-link:: https://sphinx-themes.org
        :color: primary
        
        Go to Sphinx Themes"""  # noqa

kitchen_sink_files = [
    "admonitions.rst",
    "all_in_one_restructuredtext.py",
    "api.rst",
    "blocks.rst",
    "domains/api_c_domain.rst",
    "domains/api_cpp_domain.rst",
    "domains/api_javascript_domain.rst",
    "domains/api_python_domain.rst",
    "domains/api_restructuredtext_domain.rst",
    "generic.rst",
    "images.rst",
    "index.rst",
    "lists.rst",
    "really-long.rst",
    "structure.rst",
    "tables.rst",
    "typography.rst",
]
path_sink = Path(__file__).parent.parent / "docs" / "reference" / "kitchen-sink"
for ifile in kitchen_sink_files:
    print(f"Reading {ifile}...")
    url = f"https://github.com/sphinx-themes/sphinx-themes.org/raw/master/sample-docs/kitchen-sink/{ifile}"  # noqa
    text = urlopen(url).read().decode()
    # The sphinx-themes docs expect Furo to be installed, so we overwrite with this path
    text = text.replace("src/furo", "src/plone_sphinx_theme")
    # Add introductory message directing people to Sphinx Themes
    if "index" in ifile:
        text = text.replace("============", "============\n\n" + EXTRA_MESSAGE)
    f = Path(path_sink / f"{ifile}")
    f.parent.mkdir(parents=True, exist_ok=True)  # Create directory if it doesn't exist
    f.open("w")
    f.write_text(text)

print(f"Finished updating {len(kitchen_sink_files)} files...")
