from urllib.request import urlopen
from pathlib import Path

EXTRA_MESSAGE = """\
 * 
 * AUTOGENERATED by scripts/pdst_styles_update.py"""  # noqa

pdst_styles_files = [
    "abstracts/_accessibility.scss",
    "abstracts/_all.scss",
    "abstracts/_color.scss",
    "abstracts/_links.scss",
    "abstracts/_mixins.scss",
    "base/_base.scss",
    "components/header/_header-logo.scss",
    "components/_breadcrumbs.scss",
    "components/_icon-links.scss",
    "components/_indices.scss",
    "components/_navbar-links.scss",
    "components/_page-toc.scss",
    "components/_prev-next.scss",
    "components/_search.scss",
    "components/_searchbox.scss",
    "components/_switcher-theme.scss",
    "components/_switcher-version.scss",
    "components/_toc-inpage.scss",
    "components/_versionmodified.scss",
    "content/_admonitions.scss",
    "content/_api.scss",
    "content/_code.scss",
    "content/_figures.scss",
    "content/_footnotes.scss",
    "content/_hacks.scss",
    "content/_lists.scss",
    "content/_math.scss",
    "content/_quotes.scss",
    "content/_spans.scss",
    "content/_tables.scss",
    "content/_toctree.scss",
    "extensions/_ablog.scss",
    "extensions/_bootstrap.scss",
    "extensions/_copybutton.scss",
    "extensions/_ethical-ads.scss",
    "extensions/_execution.scss",
    "extensions/_graphviz.scss",
    "extensions/_leaflet.scss",
    "extensions/_notebooks.scss",
    "extensions/_pydata.scss",
    "extensions/_sphinx_design.scss",
    "extensions/_togglebutton.scss",
    "pages/_search.scss",
    "sections/_announcement.scss",
    "sections/_article.scss",
    "sections/_container.scss",
    "sections/_footer.scss",
    "sections/_footer-article.scss",
    "sections/_footer-content.scss",
    "sections/_header.scss",
    "sections/_header-article.scss",
    "sections/_sidebar-primary.scss",
    "sections/_sidebar-secondary.scss",
    "sections/_sidebar-toggle.scss",
    "sections/_skip-link.scss",
    "variables/_admonitions.scss",
    "variables/_bootstrap.scss",
    "variables/_color.scss",
    "variables/_fonts.scss",
    "variables/_icons.scss",
    "variables/_layout.scss",
    "variables/_versionmodified.scss",
    "pydata-sphinx-theme.scss",
]
path_pdst_styles = Path(__file__).parent.parent / "src" / "plone_sphinx_theme" / "assets" / "styles" / "pydata_sphinx_theme" / "assets" / "styles"
for ifile in pdst_styles_files:
    print(f"Reading {ifile}...")
    url = (f"https://raw.githubusercontent.com/pydata/pydata-sphinx-theme/refs/heads/main/src/pydata_sphinx_theme/assets/styles/{ifile}")  # noqa
    text = urlopen(url).read().decode()
    # Add introductory message directing people to this script
    if "index" in ifile:
        text = text.replace("All rights reserved.", "All rights reserved.\n" + EXTRA_MESSAGE)
    (path_pdst_styles / f"{ifile}").write_text(text)

print(f"Finished updating {len(pdst_styles_files)} files...")
